#!/usr/bin/env node
/**
 * Emits console-snippet.js: a self-contained IIFE to paste into DevTools on a page
 * you cannot or should not automate (LinkedIn Easy Apply, anything behind a login).
 *
 * Built from scan.js and detector.js so the three cannot drift.
 *   node build-console.js
 */
const fs = require('fs');
const path = require('path');

const strip = (f) => fs.readFileSync(path.join(__dirname, f), 'utf8')
  .replace(/if \(typeof module[\s\S]*$/, '')
  .trim();

const indent = (s) => s.replace(/\n/g, '\n  ');

const out = `/* BRIDGE console probe — generated by build-console.js, do not edit directly.
   Paste into DevTools on the page you want to inspect. Chrome may require you to
   type "allow pasting" into the console first.

   bridge.scan()          scan now, print a report
   bridge.fields()        list writable controls with their index
   bridge.fill(what, value)  write to a control, then read back from the DOM
                             'what' is an index from fields(), or part of the field name
                             radios and checkboxes need no value at all
   bridge.watchTab()      log every real Tab press: where focus went, what was skipped, and why
   bridge.steps()         every step transition the detector has seen
   bridge.export()        copy(bridge.export()) for the findings write-up
   bridge.stop()          detach the observers

   fill() never clicks submit or continue. You advance the form yourself.
*/
(() => {
  // Pasting again must not stack a second detector on top of the first: every earlier
  // paste keeps observing and logging until the page reloads.
  if (window.bridge && typeof window.bridge.stop === 'function') {
    try { window.bridge.stop(); } catch (_) { /* older build */ }
  }

  ${indent(strip('scope.js'))}

  ${indent(strip('scan.js'))}

  ${indent(strip('detector.js'))}

  ${indent(strip('act-inpage.js'))}

  ${indent(strip('tabwatch.js'))}

  function report(r) {
    r = r || SCAN();
    const bad = r.fields.filter((f) => f.barriers.length);
    console.group(\`BRIDGE scan — \${r.fields.length} fields, \${bad.length} with barriers\`);
    if (r.stepHint) console.log('step hint:', r.stepHint);
    if (r.pageBarriers.length) console.table(r.pageBarriers);
    if (bad.length) console.table(bad.map((f) => ({ tag: f.tag, type: f.type, role: f.role, name: f.name.slice(0, 40), barriers: f.barriers.join(',') })));
    const combos = r.fields.filter((f) => f.role === 'combobox' || f.tag === 'select');
    if (combos.length) console.table(combos.map((f) => ({ name: f.name.slice(0, 40), optionsWhileClosed: f.optionsAvailable })));
    console.groupEnd();
    return r;
  }

  const actLog = [];

  const detector = createDetector({
    scan: SCAN,
    onEvent: (e) => {
      const isStep = e.verdict === 'new-step';
      console.log(
        \`%c[\${isStep ? 'NEW STEP' : 'fields changed'}]\`,
        isStep ? 'color:#0a0;font-weight:bold' : 'color:#888',
        \`basis=\${e.basis} similarity=\${e.similarity} fields \${e.prevFields}->\${e.nowFields}\`,
        \`scope=\${e.scopedTo}\`,
        e.urlChanged ? '(URL CHANGED)' : '(no URL change)',
        e.stepHint || '',
        \`focus=\${e.focus}\`,
      );
    },
  });

  const actor = createActor();
  const tabWatcher = createTabWatcher();

  window.bridge = {
    scan: () => report(),
    fields: () => actor.list(),
    fill: (i, v) => actor.fill(i, v).then((r) => { if (r) actLog.push(r); return r; }),
    acts: () => actLog,
    watchTab: () => tabWatcher.start(),
    steps: () => { console.table(detector.events); return detector.events; },
    export: () => JSON.stringify({ url: location.href, capturedAt: new Date().toISOString(), events: detector.events, acts: actLog }, null, 2),
    stop: () => { detector.stop(); tabWatcher.stop(); console.log('bridge: detached'); },
    _SCAN: SCAN,
  };

  console.log('%cBRIDGE console probe active.', 'color:#0a0;font-weight:bold');
  console.log('bridge.scan() | bridge.steps() | bridge.export() | bridge.stop()');
  report();
})();
`;

fs.writeFileSync(path.join(__dirname, 'console-snippet.js'), out);
console.log('wrote console-snippet.js', fs.statSync(path.join(__dirname, 'console-snippet.js')).size, 'bytes');
