/* BRIDGE console probe — generated by build-console.js, do not edit directly.
   Paste into DevTools on the page you want to inspect. Chrome may require you to
   type "allow pasting" into the console first.

   bridge.scan()     scan now, print a report
   bridge.steps()    every step transition the detector has seen
   bridge.export()   copy(bridge.export()) to get JSON for the findings write-up
   bridge.stop()     detach the observers
*/
(() => {
  /**
   * BRIDGE SCAN prototype.
   *
   * This is the same logic the content script will run, extracted so it can be
   * validated against real portals from Node before it ships in the extension.
   * Keep it dependency-free and side-effect-free: it must be `page.evaluate`-able
   * and equally injectable into a content script.
   */
  
  function SCAN() {
    const out = { url: location.href, scannedAt: new Date().toISOString(), fields: [], pageBarriers: [], stepHint: null };
  
    const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
    const txt = (el) => clean(el && el.textContent).slice(0, 160);
  
    const visible = (el) => {
      const r = el.getBoundingClientRect();
      const s = getComputedStyle(el);
      return r.width > 1 && r.height > 1 && s.visibility !== 'hidden' && s.display !== 'none' && s.opacity !== '0';
    };
  
    // Anything inside an aria-hidden subtree is invisible to a screen reader, so it
    // is neither a field we can offer nor a barrier worth reporting. Skipping these
    // removes the react-select "required input" false positives.
    const ariaHidden = (el) => !!el.closest('[aria-hidden="true"]');
  
    // --- accessible name (subset of accname, enough to decide "is this named?") ---
    function accName(el) {
      const lb = el.getAttribute('aria-labelledby');
      if (lb) {
        const t = lb.split(/\s+/).map((id) => document.getElementById(id)).filter(Boolean).map(txt).join(' ');
        if (t) return { name: t, src: 'aria-labelledby' };
      }
      const al = el.getAttribute('aria-label');
      if (al && al.trim()) return { name: al.trim(), src: 'aria-label' };
      if (el.id) {
        const l = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
        if (l && txt(l)) return { name: txt(l), src: 'label-for' };
      }
      const wrap = el.closest('label');
      if (wrap && txt(wrap)) return { name: txt(wrap), src: 'label-wrap' };
      if (el.getAttribute('title')) return { name: el.getAttribute('title'), src: 'title' };
      // A placeholder is not an accessible name in practice: it disappears on input
      // and several screen readers skip it. Treated as a barrier, not a name.
      if (el.placeholder) return { name: el.placeholder, src: 'placeholder' };
      return { name: '', src: 'none' };
    }
  
    const NATIVE = 'input,select,textarea';
    const ARIA = '[role=combobox],[role=listbox],[role=slider],[role=checkbox],[role=radio],[role=textbox],[role=spinbutton],[role=switch]';
  
    const candidates = new Set([...document.querySelectorAll(NATIVE), ...document.querySelectorAll(ARIA)]);
  
    // Custom widgets: looks clickable, is named like a control, contains no real control.
    document.querySelectorAll('div,span,li').forEach((el) => {
      if (candidates.has(el) || !visible(el)) return;
      if (getComputedStyle(el).cursor !== 'pointer') return;
      const cls = typeof el.className === 'string' ? el.className : '';
      if (!/select|dropdown|combo|picker|slider|upload|dropzone|drag/i.test(cls)) return;
      if (el.querySelector(`${NATIVE},[role],button,a[href]`)) return;
      candidates.add(el);
    });
  
    for (const el of candidates) {
      if (!visible(el) || ariaHidden(el)) continue;
      const tag = el.tagName.toLowerCase();
      const type = (el.getAttribute('type') || '').toLowerCase();
      if (tag === 'input' && ['hidden', 'submit', 'button', 'reset'].includes(type)) continue;
  
      const { name, src } = accName(el);
      const role = el.getAttribute('role') || '';
      const nativelyFocusable = ['input', 'select', 'textarea', 'button', 'a'].includes(tag);
      const focusable = el.tabIndex >= 0 || (nativelyFocusable && el.tabIndex !== -1);
      const barriers = [];
  
      if (!name) barriers.push('missing-label');
      else if (src === 'placeholder') barriers.push('label-placeholder-only');
      if (!focusable) barriers.push('not-keyboard-operable');
  
      const cls = typeof el.className === 'string' ? el.className : '';
      if (tag !== 'select' && /select|dropdown|combo|picker/i.test(cls) && !/combobox|listbox/.test(role)) {
        barriers.push('custom-dropdown-no-role');
      }
  
      // Can we enumerate options without driving the widget? Usually not — see
      // findings: every react-select on Greenhouse returns 0 here.
      let options = null;
      if (tag === 'select') options = [...el.options].map((o) => clean(o.text));
      else if (role === 'combobox') {
        const owns = el.getAttribute('aria-controls') || el.getAttribute('aria-owns');
        const menu = owns ? document.getElementById(owns) : null;
        options = menu ? [...menu.querySelectorAll('[role=option]')].map(txt) : [];
      }
  
      out.fields.push({
        tag, type, role,
        name: name || '(none)',
        labelSource: src,
        required: el.required || el.getAttribute('aria-required') === 'true',
        focusable,
        optionsAvailable: options ? options.length : null,
        options: options && options.length ? options.slice(0, 12) : undefined,
        barriers,
      });
    }
  
    // --- checkbox / radio groups with no programmatic group name ---
    const groups = {};
    document.querySelectorAll('input[type=checkbox],input[type=radio]').forEach((i) => {
      if (i.name) (groups[i.name] ||= []).push(i);
    });
    for (const [name, els] of Object.entries(groups)) {
      if (els.length < 2) continue;
      const fs = els[0].closest('fieldset,[role=group],[role=radiogroup]');
      const named = fs && (fs.querySelector('legend') || fs.getAttribute('aria-label') || fs.getAttribute('aria-labelledby'));
      if (!named) out.pageBarriers.push({ rule: 'group-not-labelled', severity: 'blocking', name, count: els.length });
    }
  
    // --- uploaders: a drop zone whose file input is unreachable ---
    document.querySelectorAll('input[type=file]').forEach((inp) => {
      const { name } = accName(inp);
      const reachable = inp.tabIndex !== -1 && visible(inp);
      const hasTrigger = inp.id && document.querySelector(`label[for="${CSS.escape(inp.id)}"]`);
      if (!reachable && !hasTrigger) {
        out.pageBarriers.push({
          rule: 'drag-drop-only', severity: 'blocking',
          detail: `file input tabIndex=${inp.tabIndex}, accessible name=${name || 'none'}, no labelled trigger`,
        });
      }
    });
  
    // --- a popup that is not a dialog (the VietnamWorks barrier) ---
    document.querySelectorAll('[class*=popup],[class*=Popup],[class*=modal],[class*=Modal]').forEach((el) => {
      if (!visible(el) || ariaHidden(el)) return;
      if (el.closest('[role=dialog],[role=alertdialog],[aria-modal=true]')) return;
      if (!el.querySelector(NATIVE)) return; // only care if it asks for input
      out.pageBarriers.push({
        rule: 'modal-without-dialog-role', severity: 'blocking',
        detail: `${el.className}`.slice(0, 60) + ' — no role=dialog/aria-modal; nothing announces it',
      });
    });
  
    if (document.querySelector('iframe[src*=recaptcha],iframe[src*=hcaptcha],[class*=h-captcha],[class*=g-recaptcha]')) {
      out.pageBarriers.push({ rule: 'captcha', severity: 'blocking' });
    }
    document.querySelectorAll('iframe').forEach((f) => {
      try {
        if (!f.contentDocument) out.pageBarriers.push({ rule: 'cross-origin-frame', severity: 'blocking', src: (f.src || '').slice(0, 90) });
      } catch (_) { /* cross-origin by definition */ }
    });
  
    // --- step indicator: how we learn the shape of a multi-step journey ---
    const wdBar = document.querySelector('[data-automation-id=progressBar]');
    const current = document.querySelector('[aria-current=step]');
    const bar = document.querySelector('progress,[role=progressbar]');
    // Portals phrase this differently: Workday "step 1 of 6", LinkedIn Easy Apply "1/4 pages".
    const body = document.body.innerText;
    const m = body.match(/step\s+(\d+)\s+of\s+(\d+)/i)
      || body.match(/(\d+)\s*(?:of|\/)\s*(\d+)\s*(?:pages?|steps?)/i)
      || body.match(/page\s+(\d+)\s*(?:of|\/)\s*(\d+)/i);
  
    if (wdBar) {
      out.stepHint = {
        via: 'workday-progressBar',
        steps: [...wdBar.querySelectorAll('li')].map((li) => clean(li.innerText)),
        activeIndex: [...wdBar.querySelectorAll('li')].findIndex((li) => li.getAttribute('data-automation-id') === 'progressBarActiveStep'),
      };
    } else if (current) {
      out.stepHint = { via: 'aria-current=step', text: txt(current) };
    } else if (m) {
      out.stepHint = { via: 'text', text: m[0], index: +m[1], total: +m[2] };
    } else if (bar) {
      out.stepHint = {
        via: 'progressbar',
        now: bar.getAttribute('aria-valuenow') ?? bar.value,
        max: bar.getAttribute('aria-valuemax') ?? bar.max,
        // A progress bar with no accessible name or value tells a screen reader nothing.
        named: !!(bar.getAttribute('aria-label') || bar.getAttribute('aria-labelledby')),
      };
    }
  
    return out;
  }

  /**
   * BRIDGE step detector (spec §6.5).
   *
   * Collapses three transition mechanisms — full navigation, SPA routing, and
   * in-place DOM swap — into one `new-step` / `fields-changed` decision.
   *
   * Measured against LinkedIn Easy Apply, which exposed two failures in the naive
   * version and drove the design here:
   *
   *   1. Fingerprinting `document` counts the page BEHIND a modal. LinkedIn's search
   *      boxes and nav persist across every step, so a genuine step change measured
   *      0.63 similar and was classified "same step". Scope to the dialog or form.
   *   2. Counting duplicate keys with Array.filter inflates the ratio past what the
   *      previous field set could possibly match. Compare sets, via Jaccard.
   *
   * And the lesson that outranks both: when the page publishes a step index, that is
   * ground truth. The similarity heuristic is the fallback for pages that do not.
   */
  function createDetector({ scan, onEvent, threshold = 0.4, debounceMs = 350 }) {
    // Only the region that actually swaps. A modal dialog wins over the form,
    // because on LinkedIn the form behind it never goes away.
    const scope = () =>
      document.querySelector('[role=dialog][aria-modal="true"]') ||
      document.querySelector('[role=dialog]') ||
      document.querySelector('form') ||
      document.body;
  
    const SEL = 'input,select,textarea,[role=combobox],[role=checkbox],[role=radio],[role=slider],[role=spinbutton]';
  
    const key = (e) => {
      const name = e.getAttribute('aria-label') || e.name || e.id || e.dataset.automationId || '';
      return `${e.tagName}:${e.type || e.getAttribute('role') || ''}:${name}`;
    };
  
    // A Set: two identically-keyed radios are one signal, not two.
    const fingerprint = () =>
      new Set([...scope().querySelectorAll(SEL)].filter((e) => e.offsetParent !== null).map(key));
  
    const jaccard = (a, b) => {
      const union = new Set([...a, ...b]).size;
      if (!union) return 1;
      return [...a].filter((k) => b.has(k)).length / union;
    };
  
    const stepIndexOf = (r) => (r && r.stepHint && typeof r.stepHint.index === 'number' ? r.stepHint.index : null);
  
    let prev = fingerprint();
    let prevStepIndex = stepIndexOf(scan());
    let lastUrl = location.href;
    const events = [];
  
    function evaluate(reason) {
      const now = fingerprint();
      const scanned = scan();
      const nowStepIndex = stepIndexOf(scanned);
  
      const sameSet = now.size === prev.size && [...now].every((k) => prev.has(k));
      const indexMoved = nowStepIndex !== null && prevStepIndex !== null && nowStepIndex !== prevStepIndex;
  
      // Nothing changed, and the page did not claim a new step: not an event.
      if (sameSet && !indexMoved) return null;
  
      const similarity = jaccard(prev, now);
      const verdict = indexMoved ? 'new-step'
        : similarity < threshold ? 'new-step'
        : 'fields-changed';
  
      const ev = {
        at: new Date().toISOString().slice(11, 19),
        reason,
        verdict,
        // why we decided: the page told us, or we inferred it
        basis: indexMoved ? 'step-index' : 'field-similarity',
        similarity: +similarity.toFixed(2),
        prevFields: prev.size,
        nowFields: now.size,
        scopedTo: scope() === document.body ? 'body' : (scope().getAttribute('role') || scope().tagName.toLowerCase()),
        stepIndex: nowStepIndex,
        stepHint: scanned.stepHint,
        urlChanged: location.href !== lastUrl,
        focus: document.activeElement
          ? `${document.activeElement.tagName} "${(document.activeElement.getAttribute('aria-label') || document.activeElement.innerText || '').replace(/\s+/g, ' ').trim().slice(0, 40)}"`
          : 'none',
        pageBarriers: scanned.pageBarriers.map((b) => b.rule),
        fieldBarriers: scanned.fields.filter((f) => f.barriers.length).length,
      };
  
      prev = now;
      prevStepIndex = nowStepIndex;
      lastUrl = location.href;
      events.push(ev);
      if (onEvent) onEvent(ev);
      return ev;
    }
  
    for (const m of ['pushState', 'replaceState']) {
      const orig = history[m];
      history[m] = function () { const r = orig.apply(this, arguments); setTimeout(() => evaluate('history.' + m), 400); return r; };
    }
    const onPop = () => setTimeout(() => evaluate('popstate'), 400);
    addEventListener('popstate', onPop);
  
    let t;
    const mo = new MutationObserver(() => { clearTimeout(t); t = setTimeout(() => evaluate('mutation'), debounceMs); });
    mo.observe(document.body, { childList: true, subtree: true });
  
    return {
      events,
      evaluate,
      stop() { mo.disconnect(); removeEventListener('popstate', onPop); },
    };
  }

  function report(r) {
    r = r || SCAN();
    const bad = r.fields.filter((f) => f.barriers.length);
    console.group(`BRIDGE scan — ${r.fields.length} fields, ${bad.length} with barriers`);
    if (r.stepHint) console.log('step hint:', r.stepHint);
    if (r.pageBarriers.length) console.table(r.pageBarriers);
    if (bad.length) console.table(bad.map((f) => ({ tag: f.tag, type: f.type, role: f.role, name: f.name.slice(0, 40), barriers: f.barriers.join(',') })));
    const combos = r.fields.filter((f) => f.role === 'combobox' || f.tag === 'select');
    if (combos.length) console.table(combos.map((f) => ({ name: f.name.slice(0, 40), optionsWhileClosed: f.optionsAvailable })));
    console.groupEnd();
    return r;
  }

  const detector = createDetector({
    scan: SCAN,
    onEvent: (e) => {
      const isStep = e.verdict === 'new-step';
      console.log(
        `%c[${isStep ? 'NEW STEP' : 'fields changed'}]`,
        isStep ? 'color:#0a0;font-weight:bold' : 'color:#888',
        `basis=${e.basis} similarity=${e.similarity} fields ${e.prevFields}->${e.nowFields}`,
        `scope=${e.scopedTo}`,
        e.urlChanged ? '(URL CHANGED)' : '(no URL change)',
        e.stepHint || '',
        `focus=${e.focus}`,
      );
    },
  });

  window.bridge = {
    scan: () => report(),
    steps: () => { console.table(detector.events); return detector.events; },
    export: () => JSON.stringify({ url: location.href, capturedAt: new Date().toISOString(), events: detector.events }, null, 2),
    stop: () => { detector.stop(); console.log('bridge: detached'); },
    _SCAN: SCAN,
  };

  console.log('%cBRIDGE console probe active.', 'color:#0a0;font-weight:bold');
  console.log('bridge.scan() | bridge.steps() | bridge.export() | bridge.stop()');
  report();
})();
