/* BRIDGE console probe — generated by build-console.js, do not edit directly.
   Paste into DevTools on the page you want to inspect. Chrome may require you to
   type "allow pasting" into the console first.

   bridge.scan()          scan now, print a report
   bridge.fields()        list writable controls with their index
   bridge.fill(what, value)  write to a control, then read back from the DOM
                             'what' is an index from fields(), or part of the field name
                             radios and checkboxes need no value at all
   bridge.watchTab()      log every real Tab press: where focus went, what was skipped, and why
   bridge.steps()         every step transition the detector has seen
   bridge.export()        copy(bridge.export()) for the findings write-up
   bridge.stop()          detach the observers

   fill() never clicks submit or continue. You advance the form yourself.
*/
(() => {
  // Pasting again must not stack a second detector on top of the first: every earlier
  // paste keeps observing and logging until the page reloads.
  if (window.bridge && typeof window.bridge.stop === 'function') {
    try { window.bridge.stop(); } catch (_) { /* older build */ }
  }

  /**
   * Picks the region of the page that holds the application form.
   *
   * Everything downstream depends on this: fingerprinting the whole document counts the
   * page behind a modal and suppresses step detection (§6.5), while trusting the first
   * [role=dialog] picks up cookie banners and consent popups that hold no controls at all
   * — measured on Greenhouse, which has exactly such a dialog.
   *
   * So: prefer the narrowest container that actually contains form controls.
   */
  function formScope(selector) {
    const SEL = selector || 'input,select,textarea,[role=combobox],[role=checkbox],[role=radio],[role=slider],[role=spinbutton]';
  
    const controlCount = (el) =>
      [...el.querySelectorAll(SEL)]
        .filter((e) => e.offsetParent !== null)
        .filter((e) => !(e.tagName === 'INPUT' && ['hidden', 'submit', 'button', 'reset'].includes(e.type)))
        .length;
  
    // Narrowest first. A modal dialog wins when it holds controls, because the form
    // behind it does not go away between steps.
    //
    // `<dialog>` must be matched by tag as well as by role: the native element has an
    // implicit dialog role but no role ATTRIBUTE, so '[role=dialog]' does not match it.
    // LinkedIn Easy Apply uses a native <dialog>, and missing it scoped every measurement
    // to <body> — which silently counted the job-search page behind the modal.
    const candidates = [
      ...document.querySelectorAll('dialog[open]'),
      ...document.querySelectorAll('[role=dialog][aria-modal="true"]'),
      ...document.querySelectorAll('dialog'),
      ...document.querySelectorAll('[role=dialog]'),
      ...document.querySelectorAll('[aria-modal="true"]'),
      ...document.querySelectorAll('form'),
    ].filter((el) => el.offsetParent !== null || (el.tagName === 'DIALOG' && el.open));
  
    for (const el of candidates) {
      if (controlCount(el) > 0) return el;
    }
    return document.body;
  }

  /**
   * BRIDGE SCAN prototype.
   *
   * This is the same logic the content script will run, extracted so it can be
   * validated against real portals from Node before it ships in the extension.
   * Keep it dependency-free and side-effect-free: it must be `page.evaluate`-able
   * and equally injectable into a content script.
   */
  
  function SCAN() {
    const out = { url: location.href, scannedAt: new Date().toISOString(), fields: [], pageBarriers: [], stepHint: null };
  
    const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
    const txt = (el) => clean(el && el.textContent).slice(0, 160);
  
    const visible = (el) => {
      const r = el.getBoundingClientRect();
      const s = getComputedStyle(el);
      return r.width > 1 && r.height > 1 && s.visibility !== 'hidden' && s.display !== 'none' && s.opacity !== '0';
    };
  
    // Anything inside an aria-hidden subtree is invisible to a screen reader, so it
    // is neither a field we can offer nor a barrier worth reporting. Skipping these
    // removes the react-select "required input" false positives.
    const ariaHidden = (el) => !!el.closest('[aria-hidden="true"]');
  
    // --- accessible name (subset of accname, enough to decide "is this named?") ---
    function accName(el) {
      const lb = el.getAttribute('aria-labelledby');
      if (lb) {
        const t = lb.split(/\s+/).map((id) => document.getElementById(id)).filter(Boolean).map(txt).join(' ');
        if (t) return { name: t, src: 'aria-labelledby' };
      }
      const al = el.getAttribute('aria-label');
      if (al && al.trim()) return { name: al.trim(), src: 'aria-label' };
      if (el.id) {
        const l = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
        if (l && txt(l)) return { name: txt(l), src: 'label-for' };
      }
      const wrap = el.closest('label');
      if (wrap && txt(wrap)) return { name: txt(wrap), src: 'label-wrap' };
      if (el.getAttribute('title')) return { name: el.getAttribute('title'), src: 'title' };
      // A placeholder is not an accessible name in practice: it disappears on input
      // and several screen readers skip it. Treated as a barrier, not a name.
      if (el.placeholder) return { name: el.placeholder, src: 'placeholder' };
      return { name: '', src: 'none' };
    }
  
    const NATIVE = 'input,select,textarea';
    const ARIA = '[role=combobox],[role=listbox],[role=slider],[role=checkbox],[role=radio],[role=textbox],[role=spinbutton],[role=switch]';
  
    const candidates = new Set([...document.querySelectorAll(NATIVE), ...document.querySelectorAll(ARIA)]);
  
    // Custom widgets: looks clickable, is named like a control, contains no real control.
    document.querySelectorAll('div,span,li').forEach((el) => {
      if (candidates.has(el) || !visible(el)) return;
      if (getComputedStyle(el).cursor !== 'pointer') return;
      const cls = typeof el.className === 'string' ? el.className : '';
      if (!/select|dropdown|combo|picker|slider|upload|dropzone|drag/i.test(cls)) return;
      if (el.querySelector(`${NATIVE},[role],button,a[href]`)) return;
      candidates.add(el);
    });
  
    for (const el of candidates) {
      if (!visible(el) || ariaHidden(el)) continue;
      const tag = el.tagName.toLowerCase();
      const type = (el.getAttribute('type') || '').toLowerCase();
      if (tag === 'input' && ['hidden', 'submit', 'button', 'reset'].includes(type)) continue;
  
      const { name, src } = accName(el);
      const role = el.getAttribute('role') || '';
      const nativelyFocusable = ['input', 'select', 'textarea', 'button', 'a'].includes(tag);
      const focusable = el.tabIndex >= 0 || (nativelyFocusable && el.tabIndex !== -1);
      const barriers = [];
  
      if (!name) barriers.push('missing-label');
      else if (src === 'placeholder') barriers.push('label-placeholder-only');
      if (!focusable) barriers.push('not-keyboard-operable');
  
      const cls = typeof el.className === 'string' ? el.className : '';
      if (tag !== 'select' && /select|dropdown|combo|picker/i.test(cls) && !/combobox|listbox/.test(role)) {
        barriers.push('custom-dropdown-no-role');
      }
  
      // Can we enumerate options without driving the widget? Usually not — see
      // findings: every react-select on Greenhouse returns 0 here.
      let options = null;
      if (tag === 'select') options = [...el.options].map((o) => clean(o.text));
      else if (role === 'combobox') {
        const owns = el.getAttribute('aria-controls') || el.getAttribute('aria-owns');
        const menu = owns ? document.getElementById(owns) : null;
        options = menu ? [...menu.querySelectorAll('[role=option]')].map(txt) : [];
      }
  
      out.fields.push({
        tag, type, role,
        name: name || '(none)',
        labelSource: src,
        required: el.required || el.getAttribute('aria-required') === 'true',
        focusable,
        optionsAvailable: options ? options.length : null,
        options: options && options.length ? options.slice(0, 12) : undefined,
        barriers,
      });
    }
  
    // --- checkbox / radio groups with no programmatic group name ---
    const groups = {};
    document.querySelectorAll('input[type=checkbox],input[type=radio]').forEach((i) => {
      if (i.name) (groups[i.name] ||= []).push(i);
    });
    for (const [name, els] of Object.entries(groups)) {
      if (els.length < 2) continue;
      const fs = els[0].closest('fieldset,[role=group],[role=radiogroup]');
      const named = fs && (fs.querySelector('legend') || fs.getAttribute('aria-label') || fs.getAttribute('aria-labelledby'));
      if (!named) out.pageBarriers.push({ rule: 'group-not-labelled', severity: 'blocking', name, count: els.length });
    }
  
    // --- options within one group that share an accessible name ---
    // Measured on LinkedIn Easy Apply: a fieldset with no legend, "fixed" by putting the
    // question into aria-label on every option. aria-label overrides element contents, so
    // "Yes" and "No" are never spoken and both options announce identically. The group
    // gained a name and the options lost theirs.
    const optionGroups = new Map();
    document.querySelectorAll('[role=radio],[role=checkbox],input[type=radio],input[type=checkbox]').forEach((el) => {
      if (!visible(el) || ariaHidden(el)) return;
      const container = el.closest('fieldset,[role=radiogroup],[role=group]');
      const groupKey = container || (el.name ? `name:${el.name}` : null);
      if (!groupKey) return;
      if (!optionGroups.has(groupKey)) optionGroups.set(groupKey, []);
      optionGroups.get(groupKey).push(el);
    });
    for (const [, opts] of optionGroups) {
      if (opts.length < 2) continue;
      const names = opts.map((el) => accName(el).name).filter(Boolean);
      if (names.length < 2) continue;
      if (new Set(names).size === 1) {
        out.pageBarriers.push({
          rule: 'options-identically-named', severity: 'blocking',
          count: opts.length,
          detail: `${opts.length} options all named "${names[0].slice(0, 60)}" — the choices cannot be told apart`,
        });
      }
    }
  
    // --- uploaders ---
    // Keyboard reachability is about the tab order, not visibility. A visually hidden but
    // focusable file input is the standard accessible pattern, so being invisible is not a
    // barrier. Only tabindex=-1, disabled, display:none, visibility:hidden or inert remove
    // it from the tab order. (An earlier version conflated the two and reported a
    // tabIndex=0 input as "drag-drop-only".)
    const keyboardReachable = (el) => {
      const cs = getComputedStyle(el);
      return el.tabIndex >= 0 && !el.disabled && cs.display !== 'none' &&
        cs.visibility !== 'hidden' && !el.closest('[inert]');
    };
    document.querySelectorAll('input[type=file]').forEach((inp) => {
      const { name } = accName(inp);
      const hasTrigger = inp.id && document.querySelector(`label[for="${CSS.escape(inp.id)}"]`);
      if (hasTrigger) return;
      if (!keyboardReachable(inp)) {
        out.pageBarriers.push({
          rule: 'drag-drop-only', severity: 'blocking',
          detail: `file input is out of the tab order (tabIndex=${inp.tabIndex}) and has no labelled trigger`,
        });
      } else if (!name) {
        out.pageBarriers.push({
          rule: 'upload-unnamed', severity: 'usability',
          detail: 'file input is keyboard-reachable but has no accessible name — heard only as a generic file button',
        });
      }
    });
  
    // --- a popup that is not a dialog (the VietnamWorks barrier) ---
    document.querySelectorAll('[class*=popup],[class*=Popup],[class*=modal],[class*=Modal]').forEach((el) => {
      if (!visible(el) || ariaHidden(el)) return;
      if (el.closest('[role=dialog],[role=alertdialog],[aria-modal=true]')) return;
      if (!el.querySelector(NATIVE)) return; // only care if it asks for input
      out.pageBarriers.push({
        rule: 'modal-without-dialog-role', severity: 'blocking',
        detail: `${el.className}`.slice(0, 60) + ' — no role=dialog/aria-modal; nothing announces it',
      });
    });
  
    if (document.querySelector('iframe[src*=recaptcha],iframe[src*=hcaptcha],[class*=h-captcha],[class*=g-recaptcha]')) {
      out.pageBarriers.push({ rule: 'captcha', severity: 'blocking' });
    }
    document.querySelectorAll('iframe').forEach((f) => {
      try {
        if (!f.contentDocument) out.pageBarriers.push({ rule: 'cross-origin-frame', severity: 'blocking', src: (f.src || '').slice(0, 90) });
      } catch (_) { /* cross-origin by definition */ }
    });
  
    // --- step indicator: how we learn the shape of a multi-step journey ---
    const wdBar = document.querySelector('[data-automation-id=progressBar]');
    const current = document.querySelector('[aria-current=step]');
    const bar = document.querySelector('progress,[role=progressbar]');
    // Portals phrase this differently: Workday "step 1 of 6", LinkedIn Easy Apply "1/4 pages".
    const body = document.body.innerText;
    const m = body.match(/step\s+(\d+)\s+of\s+(\d+)/i)
      || body.match(/(\d+)\s*(?:of|\/)\s*(\d+)\s*(?:pages?|steps?)/i)
      || body.match(/page\s+(\d+)\s*(?:of|\/)\s*(\d+)/i);
  
    if (wdBar) {
      out.stepHint = {
        via: 'workday-progressBar',
        steps: [...wdBar.querySelectorAll('li')].map((li) => clean(li.innerText)),
        activeIndex: [...wdBar.querySelectorAll('li')].findIndex((li) => li.getAttribute('data-automation-id') === 'progressBarActiveStep'),
      };
    } else if (current) {
      out.stepHint = { via: 'aria-current=step', text: txt(current) };
    } else if (m) {
      out.stepHint = { via: 'text', text: m[0], index: +m[1], total: +m[2] };
    } else if (bar) {
      out.stepHint = {
        via: 'progressbar',
        now: bar.getAttribute('aria-valuenow') ?? bar.value,
        max: bar.getAttribute('aria-valuemax') ?? bar.max,
        // A progress bar with no accessible name or value tells a screen reader nothing.
        named: !!(bar.getAttribute('aria-label') || bar.getAttribute('aria-labelledby')),
      };
    }
  
    return out;
  }

  /**
   * BRIDGE step detector (spec §6.5).
   *
   * Collapses three transition mechanisms — full navigation, SPA routing, and
   * in-place DOM swap — into one `new-step` / `fields-changed` decision.
   *
   * Measured against LinkedIn Easy Apply, which exposed two failures in the naive
   * version and drove the design here:
   *
   *   1. Fingerprinting `document` counts the page BEHIND a modal. LinkedIn's search
   *      boxes and nav persist across every step, so a genuine step change measured
   *      0.63 similar and was classified "same step". Scope to the dialog or form.
   *   2. Counting duplicate keys with Array.filter inflates the ratio past what the
   *      previous field set could possibly match. Compare sets, via Jaccard.
   *
   * And the lesson that outranks both: when the page publishes a step index, that is
   * ground truth. The similarity heuristic is the fallback for pages that do not.
   */
  function createDetector({ scan, onEvent, threshold = 0.4, debounceMs = 350 }) {
    const SEL = 'input,select,textarea,[role=combobox],[role=checkbox],[role=radio],[role=slider],[role=spinbutton]';
  
    // Only the region that actually swaps — see scope.js for why this is not just
    // "the first dialog".
    const scope = () => formScope(SEL);
  
    const key = (e) => {
      const name = e.getAttribute('aria-label') || e.name || e.id || e.dataset.automationId || '';
      return `${e.tagName}:${e.type || e.getAttribute('role') || ''}:${name}`;
    };
  
    // A Set: two identically-keyed radios are one signal, not two.
    const fingerprint = () =>
      new Set([...scope().querySelectorAll(SEL)].filter((e) => e.offsetParent !== null).map(key));
  
    const jaccard = (a, b) => {
      const union = new Set([...a, ...b]).size;
      if (!union) return 1;
      return [...a].filter((k) => b.has(k)).length / union;
    };
  
    const stepIndexOf = (r) => (r && r.stepHint && typeof r.stepHint.index === 'number' ? r.stepHint.index : null);
  
    let prev = fingerprint();
    let prevStepIndex = stepIndexOf(scan());
    let lastUrl = location.href;
    const events = [];
  
    function evaluate(reason) {
      const now = fingerprint();
      const scanned = scan();
      const nowStepIndex = stepIndexOf(scanned);
  
      const sameSet = now.size === prev.size && [...now].every((k) => prev.has(k));
      const indexMoved = nowStepIndex !== null && prevStepIndex !== null && nowStepIndex !== prevStepIndex;
  
      // Nothing changed, and the page did not claim a new step: not an event.
      if (sameSet && !indexMoved) return null;
  
      const similarity = jaccard(prev, now);
      const verdict = indexMoved ? 'new-step'
        : similarity < threshold ? 'new-step'
        : 'fields-changed';
  
      const ev = {
        at: new Date().toISOString().slice(11, 19),
        reason,
        verdict,
        // why we decided: the page told us, or we inferred it
        basis: indexMoved ? 'step-index' : 'field-similarity',
        similarity: +similarity.toFixed(2),
        prevFields: prev.size,
        nowFields: now.size,
        scopedTo: scope() === document.body ? 'body' : (scope().getAttribute('role') || scope().tagName.toLowerCase()),
        stepIndex: nowStepIndex,
        stepHint: scanned.stepHint,
        urlChanged: location.href !== lastUrl,
        focus: document.activeElement
          ? `${document.activeElement.tagName} "${(document.activeElement.getAttribute('aria-label') || document.activeElement.innerText || '').replace(/\s+/g, ' ').trim().slice(0, 40)}"`
          : 'none',
        pageBarriers: scanned.pageBarriers.map((b) => b.rule),
        fieldBarriers: scanned.fields.filter((f) => f.barriers.length).length,
      };
  
      prev = now;
      prevStepIndex = nowStepIndex;
      lastUrl = location.href;
      events.push(ev);
      if (onEvent) onEvent(ev);
      return ev;
    }
  
    for (const m of ['pushState', 'replaceState']) {
      const orig = history[m];
      history[m] = function () { const r = orig.apply(this, arguments); setTimeout(() => evaluate('history.' + m), 400); return r; };
    }
    const onPop = () => setTimeout(() => evaluate('popstate'), 400);
    addEventListener('popstate', onPop);
  
    let t;
    const mo = new MutationObserver(() => { clearTimeout(t); t = setTimeout(() => evaluate('mutation'), debounceMs); });
    mo.observe(document.body, { childList: true, subtree: true });
  
    return {
      events,
      evaluate,
      stop() { mo.disconnect(); removeEventListener('popstate', onPop); },
    };
  }

  /**
   * ACT strategies (spec §6.3), runnable in-page.
   *
   * Lets you answer "can BRIDGE actually write to this control?" on a portal you can
   * only reach by hand. Every write is followed by a read-back FROM THE DOM, which is
   * what VERIFY does and what catches a widget that silently ignored the write.
   *
   * Fills fields. Never clicks a submit or continue control.
   */
  function createActor() {
    const SEL = 'input,select,textarea,[role=combobox],[role=checkbox],[role=radio],[role=slider],[role=spinbutton]';
  
    const scope = () => formScope(SEL);
  
    const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
    const visible = (el) => el.offsetParent !== null;
  
    const name = (el) => {
      const lb = el.getAttribute('aria-labelledby');
      if (lb) {
        const t = lb.split(/\s+/).map((i) => document.getElementById(i)).filter(Boolean).map((n) => clean(n.textContent)).join(' ');
        if (t) return t;
      }
      if (el.getAttribute('aria-label')) return el.getAttribute('aria-label');
      if (el.id) { const l = document.querySelector(`label[for="${CSS.escape(el.id)}"]`); if (l) return clean(l.textContent); }
      const w = el.closest('label'); if (w) return clean(w.textContent);
      return el.placeholder || '(unnamed)';
    };
  
    const els = () => {
      const all = [...scope().querySelectorAll(SEL)].filter(visible)
        .filter((e) => !(e.tagName === 'INPUT' && ['hidden', 'submit', 'button', 'reset'].includes(e.type)));
      // Drop a control nested inside another control: an ARIA wrapper and the native
      // input it contains are one choice to the user, not two.
      return all.filter((e) => !all.some((o) => o !== e && o.contains(e)));
    };
  
    function list() {
      const rows = els().map((e, i) => ({
        i, tag: e.tagName.toLowerCase(), type: e.type || e.getAttribute('role') || '',
        name: name(e).slice(0, 90), value: (e.value ?? '').toString().slice(0, 25),
      }));
      console.table(rows);
      return rows;
    }
  
    const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  
    async function fill(target, value) {
      const all = els();
      // `target` may be an index from bridge.fields(), or any part of the field's name.
      let el = null;
      if (typeof target === 'number') {
        el = all[target];
      } else if (typeof target === 'string') {
        const q = target.toLowerCase();
        const hits = all.filter((e) => name(e).toLowerCase().includes(q));
        if (hits.length > 1) {
          const sameName = new Set(hits.map((e) => name(e))).size === 1;
          console.warn(`"${target}" matches ${hits.length} controls; use an index instead:`);
          console.table(hits.map((e) => ({ i: all.indexOf(e), name: name(e).slice(0, 90) })));
          if (sameName) {
            console.warn(
              'These controls share an accessible name, so a screen reader announces them identically.',
              '\n   If they are the options of one question that is a blocking barrier — confirm the',
              '\n   computed name in DevTools > Elements > Accessibility before reporting it.',
            );
          }
          return null;
        }
        el = hits[0];
        if (el) console.log(`   matched "${name(el).slice(0, 45)}" (index ${all.indexOf(el)})`);
      }
      if (!el) {
        console.warn(
          `no control matching ${JSON.stringify(target)}. This form has ${all.length} control(s), indices 0-${all.length - 1}:`,
        );
        list();
        console.warn('Indices come from bridge.fields() and change on every step — re-run it after each Next.');
        return null;
      }
      const label = name(el);
      const tag = el.tagName.toLowerCase();
      const role = el.getAttribute('role') || '';
      const isToggle = ['checkbox', 'radio', 'switch'].includes(role) ||
                       (tag === 'input' && ['checkbox', 'radio'].includes(el.type));
  
      // Only a toggle may omit the value. Without this guard a missing argument is
      // stringified and written into the live page as the literal text "undefined".
      if (!isToggle && (value === undefined || value === null)) {
        console.warn(
          `"${label.slice(0, 45)}" needs a value: bridge.fill(${JSON.stringify(target)}, 'your value').`,
          '\n   Only radios, checkboxes and switches can be filled without one.',
        );
        return null;
      }
  
      let strategy, readBack, ok;
  
      if (tag === 'select') {
        strategy = 'native-select';
        const opt = [...el.options].find((o) => o.text.trim().toLowerCase().includes(String(value).toLowerCase()));
        if (opt) { el.value = opt.value; el.dispatchEvent(new Event('change', { bubbles: true })); }
        await sleep(400);
        readBack = el.options[el.selectedIndex] && el.options[el.selectedIndex].text.trim();
        ok = !!readBack && readBack.toLowerCase().includes(String(value).toLowerCase());
  
      } else if (['checkbox', 'radio', 'switch'].includes(role) ||
                 (tag === 'input' && ['checkbox', 'radio'].includes(el.type))) {
        // A radio or checkbox takes no value — activating it IS the write.
        // Prefer the native input when an ARIA wrapper contains one: LinkedIn renders
        // div[role=radio] around a real input, and clicking the input is what the
        // page's own handler expects.
        const native = (tag === 'input') ? el : el.querySelector('input[type=radio],input[type=checkbox]');
        const hit = native || el;
        strategy = native && native !== el ? 'click (native input inside ARIA wrapper)' : 'click';
        hit.click();
        await sleep(400);
        const checked = native ? native.checked : el.getAttribute('aria-checked') === 'true';
        readBack = checked ? 'checked' : 'not checked';
        ok = checked;
  
      } else if (role === 'combobox' || (tag !== 'input' && tag !== 'textarea')) {
        strategy = 'synthetic-mouse (open, pick option)';
        let ctrl = el;
        for (let d = 0; d < 4 && ctrl.parentElement; d++) ctrl = ctrl.parentElement;
        for (const t of ['mousedown', 'mouseup']) el.dispatchEvent(new MouseEvent(t, { bubbles: true, cancelable: true, button: 0 }));
        await sleep(600);
        const owns = el.getAttribute('aria-controls') || el.getAttribute('aria-owns');
        const menu = owns ? document.getElementById(owns) : document;
        const opts = menu ? [...menu.querySelectorAll('[role=option]')] : [];
        const target = opts.find((o) => clean(o.textContent).toLowerCase().includes(String(value).toLowerCase())) || opts[0];
        const picked = target ? clean(target.textContent) : null;
        console.log(`   menu opened with ${opts.length} options` + (picked ? `, picking ${JSON.stringify(picked)}` : ''));
        if (target) for (const t of ['mousedown', 'mouseup', 'click']) target.dispatchEvent(new MouseEvent(t, { bubbles: true, cancelable: true, button: 0 }));
        await sleep(700);
  
        // A custom combobox almost never keeps the selection on the element you wrote to:
        // react-select clears its search input and renders the choice in a sibling node.
        // So read back from the rendered widget, walking outward until we find it.
        readBack = clean(el.value);
        if (!readBack) {
          let n = el;
          for (let d = 0; d < 6 && n && !readBack; d++) {
            n = n.parentElement;
            if (!n) break;
            const shown = n.querySelector('[class*=single-value],[class*=singleValue],[class*=selected-value]');
            if (shown) { readBack = clean(shown.textContent); break; }
            // fall back to "did the widget's own text start containing what we picked?"
            if (picked && clean(n.textContent).includes(picked)) { readBack = picked; break; }
          }
        }
        readBack = (readBack || '').slice(0, 40);
        ok = !!readBack && (!picked || readBack.toLowerCase().includes(picked.toLowerCase().slice(0, 6)));
  
      } else {
        strategy = 'prototype value setter';
        const proto = tag === 'textarea' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
        Object.getOwnPropertyDescriptor(proto, 'value').set.call(el, value);
        el.dispatchEvent(new Event('input', { bubbles: true }));
        el.dispatchEvent(new Event('change', { bubbles: true }));
        await sleep(700);
        readBack = el.value;
        ok = String(readBack) === String(value);
      }
  
      console.log(
        `%c[${ok ? 'ACT PASS' : 'ACT FAIL'}]`, ok ? 'color:#0a0;font-weight:bold' : 'color:#c00;font-weight:bold',
        `"${label.slice(0, 35)}" via ${strategy}`,
        `\n   wrote: ${JSON.stringify(value)}\n   DOM read-back: ${JSON.stringify(readBack)}`,
      );
      return { index: all.indexOf(el), label, tag, role, strategy, wrote: value, readBack, ok };
    }
  
    return { list, fill };
  }

  /**
   * Tab-order diagnostic. Real keypresses only.
   *
   * Synthetic Tab events do not move focus, so tab order can only be observed while a
   * person presses the key. This watches real Tab presses and reports where focus went,
   * whether the page intercepted the key, and which controls were jumped over.
   *
   * It separates three causes that look identical to a tester:
   *   - the page removed the control from the tab order (tabindex=-1, disabled);
   *   - the page intercepts Tab and moves focus itself — a hand-rolled focus trap whose
   *     list of "tabbable" elements is incomplete. A real barrier, on every OS;
   *   - the browser's native tab order skipped a focusable control — on macOS that is
   *     the Keyboard navigation setting, not the page.
   *
   * Radios are excluded from skip detection: a radio group is one tab stop by design.
   */
  function createTabWatcher() {
    const STOPS = [
      'input:not([type=hidden]):not([type=radio])', 'select', 'textarea', 'button',
      '[role=combobox]', '[role=checkbox]', '[role=switch]',
    ].join(',');
  
    let handler = null;
  
    const describe = (el) => {
      if (!el || el === document.body || el === document.documentElement) return 'BODY (no focus)';
      const label = (el.getAttribute('aria-label') ||
        (el.labels && el.labels[0] && el.labels[0].textContent) ||
        el.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 40);
      return `${el.tagName.toLowerCase()} "${label}"`;
    };
  
    // Tab stops inside the form, in document order, with `extra` merged in at their
    // own positions so that `from` and `to` always have an index.
    const ordered = (extra) => {
      const set = new Set([...formScope().querySelectorAll(STOPS)].filter((el) => el.offsetParent !== null));
      for (const el of extra) if (el) set.add(el);
      return [...set].sort((x, y) => (x.compareDocumentPosition(y) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1));
    };
  
    // What a Tab press jumped over, following the direction of travel. A modal that
    // loops focus from its last control back to its first (or the reverse on Shift+Tab)
    // is doing its job. Measured on LinkedIn Easy Apply: Next -> Dismiss. The skipped
    // set for a wrap is only what lies AFTER `from` plus what lies BEFORE `to` — not
    // everything in between in the document, which an earlier version reported.
    const travel = (from, to, backward) => {
      const list = ordered([from, to]);
      const i = list.indexOf(from), j = list.indexOf(to);
      let skipped, wrapped;
      if (!backward) {
        wrapped = j < i;
        skipped = wrapped ? list.slice(i + 1).concat(list.slice(0, j)) : list.slice(i + 1, j);
      } else {
        wrapped = j > i;
        skipped = wrapped ? list.slice(0, i).concat(list.slice(j + 1)) : list.slice(j + 1, i);
      }
      skipped = skipped.filter((el) => !el.contains(from) && !el.contains(to) && !from.contains(el) && !to.contains(el));
      return { skipped, wrapped };
    };
  
    const removedByPage = (el) => el.tabIndex < 0 || el.disabled;
  
    function start() {
      if (handler) { console.log('already watching Tab'); return; }
      handler = (e) => {
        if (e.key !== 'Tab') return;
        const from = document.activeElement;
        setTimeout(() => {
          const to = document.activeElement;
          const intercepted = e.defaultPrevented;
          const scope = formScope();
          const lostFocus = !to || to === document.body || to === document.documentElement;
          const leftForm = !lostFocus && scope !== document.body && !scope.contains(to);
  
          const lines = [
            `${describe(from)}  ->  ${describe(to)}`,
            `   page intercepted Tab: ${intercepted}`,
          ];
  
          if (lostFocus || leftForm) {
            lines.push(lostFocus
              ? '   VERDICT: focus was dropped to the page body. Real barrier: the user is no longer anywhere.'
              : '   VERDICT: focus escaped the dialog into the page behind it. Real barrier for a modal.');
            console.log(`%c[Tab${e.shiftKey ? ' back' : ''}]%c ${lines.join('\n')}`, 'font-weight:bold', 'color:#c00');
            return;
          }
  
          const { skipped, wrapped } = travel(from, to, e.shiftKey);
          if (wrapped) lines.push(`   wrapped to the ${e.shiftKey ? 'end' : 'start'} of the dialog`);
          for (const el of skipped) {
            lines.push(`   SKIPPED ${describe(el)}  tabIndex=${el.tabIndex}${el.disabled ? ' disabled' : ''}`);
          }
  
          let verdict;
          if (!skipped.length) {
            verdict = wrapped
              ? 'VERDICT: focus looped around the dialog. Expected modal behaviour, not a barrier.'
              : 'no controls skipped';
          }
          else if (skipped.every(removedByPage)) verdict = 'VERDICT: the page removed these from the tab order (tabindex=-1 / disabled). Real barrier.';
          else if (intercepted) verdict = 'VERDICT: the page intercepted Tab and moved focus itself, jumping over focusable controls. Real barrier, on every OS.';
          else verdict = 'VERDICT: native tab order skipped focusable controls. On macOS turn on Keyboard navigation and retest; on Windows this is unexpected — report it.';
          lines.push(`   ${verdict}`);
  
          console.log(`%c[Tab${e.shiftKey ? ' back' : ''}]%c ${lines.join('\n')}`,
            'font-weight:bold', skipped.length ? 'color:#c00' : 'color:inherit');
        }, 60);
      };
      document.addEventListener('keydown', handler, true);
      console.log('Watching Tab. Click the field just before a dropdown, press Tab once, read the [Tab] line.');
    }
  
    function stop() {
      if (handler) document.removeEventListener('keydown', handler, true);
      handler = null;
    }
  
    return { start, stop };
  }

  function report(r) {
    r = r || SCAN();
    const bad = r.fields.filter((f) => f.barriers.length);
    console.group(`BRIDGE scan — ${r.fields.length} fields, ${bad.length} with barriers`);
    if (r.stepHint) console.log('step hint:', r.stepHint);
    if (r.pageBarriers.length) console.table(r.pageBarriers);
    if (bad.length) console.table(bad.map((f) => ({ tag: f.tag, type: f.type, role: f.role, name: f.name.slice(0, 40), barriers: f.barriers.join(',') })));
    const combos = r.fields.filter((f) => f.role === 'combobox' || f.tag === 'select');
    if (combos.length) console.table(combos.map((f) => ({ name: f.name.slice(0, 40), optionsWhileClosed: f.optionsAvailable })));
    console.groupEnd();
    return r;
  }

  const actLog = [];

  const detector = createDetector({
    scan: SCAN,
    onEvent: (e) => {
      const isStep = e.verdict === 'new-step';
      console.log(
        `%c[${isStep ? 'NEW STEP' : 'fields changed'}]`,
        isStep ? 'color:#0a0;font-weight:bold' : 'color:#888',
        `basis=${e.basis} similarity=${e.similarity} fields ${e.prevFields}->${e.nowFields}`,
        `scope=${e.scopedTo}`,
        e.urlChanged ? '(URL CHANGED)' : '(no URL change)',
        e.stepHint || '',
        `focus=${e.focus}`,
      );
    },
  });

  const actor = createActor();
  const tabWatcher = createTabWatcher();

  window.bridge = {
    scan: () => report(),
    fields: () => actor.list(),
    fill: (i, v) => actor.fill(i, v).then((r) => { if (r) actLog.push(r); return r; }),
    acts: () => actLog,
    watchTab: () => tabWatcher.start(),
    steps: () => { console.table(detector.events); return detector.events; },
    export: () => JSON.stringify({ url: location.href, capturedAt: new Date().toISOString(), events: detector.events, acts: actLog }, null, 2),
    stop: () => { detector.stop(); tabWatcher.stop(); console.log('bridge: detached'); },
    _SCAN: SCAN,
  };

  console.log('%cBRIDGE console probe active.', 'color:#0a0;font-weight:bold');
  console.log('bridge.scan() | bridge.steps() | bridge.export() | bridge.stop()');
  report();
})();
